// Code generated by protoc-gen-go. DO NOT EDIT.
// source: userInfo.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type User struct {
	Name                 string       `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age                  int32        `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
	Address              *Address     `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	Phone                *PhoneNumber `protobuf:"bytes,4,opt,name=phone,proto3" json:"phone,omitempty"`
	UpdatedAt            string       `protobuf:"bytes,5,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	CreatedAt            string       `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}     `json:"-"`
	XXX_unrecognized     []byte       `json:"-"`
	XXX_sizecache        int32        `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_9abb1e7c7c5082b5, []int{0}
}

func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (m *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(m, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *User) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func (m *User) GetAddress() *Address {
	if m != nil {
		return m.Address
	}
	return nil
}

func (m *User) GetPhone() *PhoneNumber {
	if m != nil {
		return m.Phone
	}
	return nil
}

func (m *User) GetUpdatedAt() string {
	if m != nil {
		return m.UpdatedAt
	}
	return ""
}

func (m *User) GetCreatedAt() string {
	if m != nil {
		return m.CreatedAt
	}
	return ""
}

type Address struct {
	Street               string   `protobuf:"bytes,1,opt,name=street,proto3" json:"street,omitempty"`
	City                 string   `protobuf:"bytes,2,opt,name=city,proto3" json:"city,omitempty"`
	State                string   `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	Zip                  string   `protobuf:"bytes,4,opt,name=zip,proto3" json:"zip,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Address) Reset()         { *m = Address{} }
func (m *Address) String() string { return proto.CompactTextString(m) }
func (*Address) ProtoMessage()    {}
func (*Address) Descriptor() ([]byte, []int) {
	return fileDescriptor_9abb1e7c7c5082b5, []int{1}
}

func (m *Address) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Address.Unmarshal(m, b)
}
func (m *Address) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Address.Marshal(b, m, deterministic)
}
func (m *Address) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Address.Merge(m, src)
}
func (m *Address) XXX_Size() int {
	return xxx_messageInfo_Address.Size(m)
}
func (m *Address) XXX_DiscardUnknown() {
	xxx_messageInfo_Address.DiscardUnknown(m)
}

var xxx_messageInfo_Address proto.InternalMessageInfo

func (m *Address) GetStreet() string {
	if m != nil {
		return m.Street
	}
	return ""
}

func (m *Address) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *Address) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *Address) GetZip() string {
	if m != nil {
		return m.Zip
	}
	return ""
}

type PhoneNumber struct {
	Primary              string            `protobuf:"bytes,1,opt,name=primary,proto3" json:"primary,omitempty"`
	Others               map[string]string `protobuf:"bytes,2,rep,name=others,proto3" json:"others,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *PhoneNumber) Reset()         { *m = PhoneNumber{} }
func (m *PhoneNumber) String() string { return proto.CompactTextString(m) }
func (*PhoneNumber) ProtoMessage()    {}
func (*PhoneNumber) Descriptor() ([]byte, []int) {
	return fileDescriptor_9abb1e7c7c5082b5, []int{2}
}

func (m *PhoneNumber) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PhoneNumber.Unmarshal(m, b)
}
func (m *PhoneNumber) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PhoneNumber.Marshal(b, m, deterministic)
}
func (m *PhoneNumber) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PhoneNumber.Merge(m, src)
}
func (m *PhoneNumber) XXX_Size() int {
	return xxx_messageInfo_PhoneNumber.Size(m)
}
func (m *PhoneNumber) XXX_DiscardUnknown() {
	xxx_messageInfo_PhoneNumber.DiscardUnknown(m)
}

var xxx_messageInfo_PhoneNumber proto.InternalMessageInfo

func (m *PhoneNumber) GetPrimary() string {
	if m != nil {
		return m.Primary
	}
	return ""
}

func (m *PhoneNumber) GetOthers() map[string]string {
	if m != nil {
		return m.Others
	}
	return nil
}

type UserRequest struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserRequest) Reset()         { *m = UserRequest{} }
func (m *UserRequest) String() string { return proto.CompactTextString(m) }
func (*UserRequest) ProtoMessage()    {}
func (*UserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_9abb1e7c7c5082b5, []int{3}
}

func (m *UserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserRequest.Unmarshal(m, b)
}
func (m *UserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserRequest.Marshal(b, m, deterministic)
}
func (m *UserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserRequest.Merge(m, src)
}
func (m *UserRequest) XXX_Size() int {
	return xxx_messageInfo_UserRequest.Size(m)
}
func (m *UserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_UserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_UserRequest proto.InternalMessageInfo

func (m *UserRequest) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type UserResponse struct {
	User                 *User    `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Status               int32    `protobuf:"varint,2,opt,name=status,proto3" json:"status,omitempty"`
	Error                string   `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *UserResponse) Reset()         { *m = UserResponse{} }
func (m *UserResponse) String() string { return proto.CompactTextString(m) }
func (*UserResponse) ProtoMessage()    {}
func (*UserResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_9abb1e7c7c5082b5, []int{4}
}

func (m *UserResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_UserResponse.Unmarshal(m, b)
}
func (m *UserResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_UserResponse.Marshal(b, m, deterministic)
}
func (m *UserResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_UserResponse.Merge(m, src)
}
func (m *UserResponse) XXX_Size() int {
	return xxx_messageInfo_UserResponse.Size(m)
}
func (m *UserResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_UserResponse.DiscardUnknown(m)
}

var xxx_messageInfo_UserResponse proto.InternalMessageInfo

func (m *UserResponse) GetUser() *User {
	if m != nil {
		return m.User
	}
	return nil
}

func (m *UserResponse) GetStatus() int32 {
	if m != nil {
		return m.Status
	}
	return 0
}

func (m *UserResponse) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterType((*User)(nil), "proto.User")
	proto.RegisterType((*Address)(nil), "proto.Address")
	proto.RegisterType((*PhoneNumber)(nil), "proto.PhoneNumber")
	proto.RegisterMapType((map[string]string)(nil), "proto.PhoneNumber.OthersEntry")
	proto.RegisterType((*UserRequest)(nil), "proto.UserRequest")
	proto.RegisterType((*UserResponse)(nil), "proto.UserResponse")
}

func init() {
	proto.RegisterFile("userInfo.proto", fileDescriptor_9abb1e7c7c5082b5)
}

var fileDescriptor_9abb1e7c7c5082b5 = []byte{
	// 394 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x6c, 0x52, 0x4d, 0x6b, 0xdb, 0x30,
	0x18, 0x9e, 0xe3, 0x2f, 0xfc, 0x6a, 0x84, 0xa1, 0x8d, 0x61, 0x02, 0xdb, 0x3c, 0x9f, 0x7c, 0xca,
	0xc0, 0x1b, 0x63, 0x6b, 0x4f, 0x29, 0x94, 0xd2, 0x4b, 0x5b, 0x04, 0xb9, 0x14, 0x42, 0x51, 0xe2,
	0xb7, 0x4d, 0x68, 0x63, 0xab, 0x92, 0x5c, 0x48, 0x7f, 0x4a, 0x7f, 0x4c, 0x7f, 0x5b, 0xd1, 0x87,
	0x21, 0xa5, 0x3d, 0xe9, 0x7d, 0x3e, 0x90, 0x9e, 0x47, 0x12, 0x8c, 0x7b, 0x85, 0xf2, 0xb4, 0xbd,
	0xee, 0xa6, 0x42, 0x76, 0xba, 0xa3, 0xb1, 0x5d, 0xca, 0xe7, 0x00, 0xa2, 0xb9, 0x42, 0x49, 0x29,
	0x44, 0x2d, 0xdf, 0x62, 0x1e, 0x14, 0x41, 0x95, 0x31, 0x3b, 0xd3, 0x4f, 0x10, 0xf2, 0x1b, 0xcc,
	0x47, 0x45, 0x50, 0xc5, 0xcc, 0x8c, 0xb4, 0x82, 0x94, 0x37, 0x8d, 0x44, 0xa5, 0xf2, 0xb0, 0x08,
	0x2a, 0x52, 0x8f, 0xdd, 0x76, 0xd3, 0x99, 0x63, 0xd9, 0x20, 0xd3, 0x0a, 0x62, 0xb1, 0xee, 0x5a,
	0xcc, 0x23, 0xeb, 0xa3, 0xde, 0x77, 0x61, 0xb8, 0xb3, 0x7e, 0xbb, 0x44, 0xc9, 0x9c, 0x81, 0x7e,
	0x03, 0xe8, 0x45, 0xc3, 0x35, 0x36, 0x57, 0x5c, 0xe7, 0xb1, 0x3d, 0x3f, 0xf3, 0xcc, 0x4c, 0x1b,
	0x79, 0x25, 0x71, 0x90, 0x13, 0x27, 0x7b, 0x66, 0xa6, 0xcb, 0x05, 0xa4, 0xfe, 0x6c, 0xfa, 0x15,
	0x12, 0xa5, 0x25, 0xa2, 0xf6, 0x25, 0x3c, 0x32, 0xd5, 0x56, 0x1b, 0xbd, 0xb3, 0x3d, 0x32, 0x66,
	0x67, 0xfa, 0x05, 0x62, 0xa5, 0xb9, 0x46, 0x5b, 0x23, 0x63, 0x0e, 0x98, 0xc2, 0x8f, 0x1b, 0x61,
	0x23, 0x67, 0xcc, 0x8c, 0xe5, 0x53, 0x00, 0x64, 0x2f, 0x33, 0xcd, 0x21, 0x15, 0x72, 0xb3, 0xe5,
	0x72, 0xe7, 0x0f, 0x19, 0x20, 0xfd, 0x0b, 0x49, 0xa7, 0xd7, 0x28, 0x55, 0x3e, 0x2a, 0xc2, 0x8a,
	0xd4, 0xdf, 0xdf, 0x36, 0x9e, 0x9e, 0x5b, 0xc3, 0x71, 0xab, 0xe5, 0x8e, 0x79, 0xf7, 0xe4, 0x3f,
	0x90, 0x3d, 0xda, 0x44, 0xb8, 0xc5, 0x61, 0x73, 0x33, 0x9a, 0xa8, 0x0f, 0xfc, 0xae, 0x47, 0x9f,
	0xdf, 0x81, 0x83, 0xd1, 0xbf, 0xa0, 0xfc, 0x09, 0xc4, 0xbc, 0x1d, 0xc3, 0xfb, 0x1e, 0x95, 0x7e,
	0xef, 0x09, 0xcb, 0x05, 0x7c, 0x74, 0x16, 0x25, 0xba, 0x56, 0x21, 0xfd, 0x01, 0x91, 0xf9, 0x08,
	0xd6, 0x43, 0x6a, 0xe2, 0x33, 0x5a, 0x8b, 0x15, 0xdc, 0x25, 0x72, 0xdd, 0x2b, 0xff, 0xec, 0x1e,
	0x99, 0x14, 0x28, 0x65, 0x27, 0x87, 0x0b, 0xb3, 0xa0, 0x3e, 0x84, 0x70, 0xae, 0x24, 0xfd, 0x03,
	0xe9, 0x09, 0x6a, 0xf7, 0x8f, 0xf6, 0xb7, 0x74, 0xc1, 0x26, 0x9f, 0x5f, 0x71, 0x2e, 0x49, 0xf9,
	0xe1, 0x88, 0x5c, 0x66, 0x5c, 0x88, 0x5f, 0x56, 0x5b, 0x26, 0x76, 0xf9, 0xfd, 0x12, 0x00, 0x00,
	0xff, 0xff, 0x13, 0x3e, 0xfe, 0xbf, 0xa8, 0x02, 0x00, 0x00,
}
